In [1]:
import pandas as pd
import json
from glob import glob

pd.set_option('display.max_columns', None)

In [3]:
file = 'data_msk/msk_2026-5.json'
with open(file) as f:
    json_str = json.load(f)

In [2]:
json_str = []
for file in glob("data_msk/*.json"):
    with open(file) as f:
        json_str.append(json.load(f))

In [3]:
print(len(json_str))

147

# dtp

In [4]:
record_path = ['results', 'region_list', 'pok_list', 'result', 'dtpcardlist', 'info_dtp']
meta = [
    ['results', 'region_list', 'reg_code'],
    ['results', 'region_list', 'reg_name'],
    ['results', 'region_list', 'pok_list', 'pok_code'],
    ['results', 'region_list', 'pok_list', 'pok_name'],
    # ['results', 'region_list', 'pok_list', 'result', 'countcard'],
    # ['results', 'region_list', 'pok_list', 'result', 'pog_v'],
    # ['results', 'region_list', 'pok_list', 'result', 'ran_v']
]
df_dtp = pd.json_normalize(
    json_str,
    record_path=record_path,
    meta=meta,
    errors='ignore'
)
df_dtp = df_dtp.rename(columns={
    'results.region_list.reg_code': 'reg_code',
    'results.region_list.reg_name': 'reg_name',
    'results.region_list.pok_list.pok_code': 'pok_code',
    'results.region_list.pok_list.pok_name': 'pok_name',
})

In [5]:
print(df_dtp.columns)

Index(['empt_number', 'date_dtp', 'time', 'coord_w', 'coord_l', 'dtpv', 'k_ts',
       'k_uch', 'pog', 'ran', 's_dtp', 'district', 'house', 'km', 'm', 'np',
       'street', 'dor', 'dor_z', 'dor_k', 'k_ul', 'ts_info', 'uch_info',
       'dor_usl.sdor', 'dor_usl.obj_dtp', 'dor_usl.ndu', 'dor_usl.factor',
       'dor_usl.spog', 'dor_usl.s_pch', 'dor_usl.osv', 'dor_usl.chom',
       'reg_code', 'reg_name', 'pok_code', 'pok_name'],
      dtype='object')

In [6]:
df_dtp.head()

,empt_number,date_dtp,time,coord_w,coord_l,dtpv,k_ts,k_uch,pog,ran,s_dtp,district,house,km,m,np,street,dor,dor_z,dor_k,k_ul,ts_info,uch_info,dor_usl.sdor,dor_usl.obj_dtp,dor_usl.ndu,dor_usl.factor,dor_usl.spog,dor_usl.s_pch,dor_usl.osv,dor_usl.chom,reg_code,reg_name,pok_code,pok_name
0,,30.10.2018,20:00,55.859556,37.602553,Наезд на велосипедиста,2,2,0,1,070,Отрадное,4,0,0,г Москва,ул Отрадная,,"Местного значения (дорога местного значения, в...",,Магистральные улицы районного значения,"[{'n_ts': '1', 'ts_s': 'Осталось на месте ДТП'...",[],[Перегон (нет объектов на месте ДТП)],"[Административные здания, Многоквартирные жилы...",[Не установлены],[Сведения отсутствуют],[Ясно],Сухое,"В темное время суток, освещение включено",Режим движения не изменялся,1145,гор. Москва,39,с пострадавшими велосипедистами
1,,26.10.2018,11:00,55.735912,37.519737,Наезд на велосипедиста,2,2,0,1,400,Дорогомилово,1Б,0,0,г Москва,пл Победы,,"Местного значения (дорога местного значения, в...",,Магистральные улицы общегородского значения,"[{'n_ts': '1', 'ts_s': 'Осталось на месте ДТП'...",[],[Внутридворовая территория],[Многоквартирные жилые дома],[Не установлены],[Сведения отсутствуют],[Пасмурно],Сухое,Светлое время суток,Режим движения не изменялся,1145,гор. Москва,39,с пострадавшими велосипедистами
2,,20.10.2018,11:20,55.796848,37.785352,Наезд на велосипедиста,2,2,0,1,740,Измайлово,7,0,0,г Москва,б-р Измайловский,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '1', 'ts_s': 'Осталось на месте ДТП'...",[],[Нерегулируемый пешеходный переход],"[Остановка общественного транспорта, Школа либ...",[Не установлены],[Сведения отсутствуют],[Ясно],Сухое,Светлое время суток,Движение частично перекрыто,1145,гор. Москва,39,с пострадавшими велосипедистами
3,,19.10.2018,18:30,55.843506,37.439239,Наезд на велосипедиста,2,2,0,1,500,Южное Тушино,19,0,0,г Москва,ул Сходненская,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '1', 'ts_s': 'Осталось на месте ДТП'...",[],[Регулируемый перекресток],"[Остановка общественного транспорта, Крупный т...",[Не установлены],[Сведения отсутствуют],[Ясно],Сухое,"В темное время суток, освещение включено",Режим движения не изменялся,1145,гор. Москва,39,с пострадавшими велосипедистами
4,,19.10.2018,10:48,55.703655,37.62032,Наезд на велосипедиста,2,2,0,1,060,Донской,4,0,0,г Москва,пер Тульский 2-й,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '2', 'ts_s': 'Осталось на месте ДТП'...",[],[Перегон (нет объектов на месте ДТП)],"[Иная образовательная организация, Нерегулируе...",[Не установлены],[Сужение проезжей части припаркованным транспо...,[Ясно],Сухое,Светлое время суток,Режим движения не изменялся,1145,гор. Москва,39,с пострадавшими велосипедистами

# ts

In [7]:
# Нормализуем ts_info отдельно, добавив номер ДТП как ключ
df_ts = pd.json_normalize(
    json_str,
    record_path=['results', 'region_list', 'pok_list', 'result', 'dtpcardlist', 'info_dtp', 'ts_info'],
    meta=[['results', 'region_list', 'pok_list', 'result', 'dtpcardlist', 'info_dtp', 'empt_number']]
)
df_ts = df_ts.rename(columns={
    'results.region_list.pok_list.result.dtpcardlist.info_dtp.empt_number': 'empt_number',
})

In [8]:
print(df_ts.columns)

Index(['n_ts', 'ts_s', 't_ts', 'm_ts', 'marka_ts', 'color', 'm_pov', 't_n',
       'r_rul', 'g_v', 'o_pf', 'ts_uch', 'empt_number'],
      dtype='object')

In [9]:
df_ts[6:20]

,n_ts,ts_s,t_ts,m_ts,marka_ts,color,m_pov,t_n,r_rul,g_v,o_pf,ts_uch,empt_number
6,1,Осталось на месте ДТП,"Е-класс (высший средний, бизнес-класс) до 4,9 м",Stealth,DODGE,Красный,,Технические неисправности отсутствуют,Полноприводные,1992,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...",
7,2,Осталось на месте ДТП,Велосипеды,,,,,Технические неисправности отсутствуют,,,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Велосипедист', 's_s...",
8,2,Осталось на месте ДТП,Велосипеды,,,Иные цвета,,Технические неисправности отсутствуют,,,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Велосипедист', 's_s...",
9,1,Осталось на месте ДТП,Фургоны,"ГАЗ 24, 24-01, 24-02, 24-03, 24-04, 24-07, 24-...",ГАЗ,Белый,,Технические неисправности отсутствуют,С задним приводом,2016,"Юридические лица, являющиеся некоммерческими о...","[{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...",
10,2,Осталось на месте ДТП,Велосипеды,,,Иные цвета,,Технические неисправности отсутствуют,,,"Юридические лица, являющиеся некоммерческими о...","[{'n_uch': '1', 'kt_uch': 'Велосипедист', 's_s...",
11,1,Осталось на месте ДТП,"D-класс (средний) до 4,6 м",Jetta,VOLKSWAGEN,Белый,,Технические неисправности отсутствуют,С передним приводом,2016,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...",
12,1,Осталось на месте ДТП,"С-класс (малый средний, компактный) до 4,3 м",Прочие модели Mitsubishi,MITSUBISHI,Черный,,Технические неисправности отсутствуют,С передним приводом,2011,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...",
13,2,Осталось на месте ДТП,Велосипеды,,,Черный,,Технические неисправности отсутствуют,Иное расположение рулевого управления,,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Велосипедист', 's_s...",
14,1,Осталось на месте ДТП,"В-класс (малый) до 3,9 м","ВАЗ 2111, 21110 (универсал), 21113, 21114",ВАЗ,Серый,,Технические неисправности отсутствуют,С передним приводом,2002,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...",
15,2,Осталось на месте ДТП,Велосипеды,,,Белый,,Технические неисправности отсутствуют,Иное расположение рулевого управления,,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Велосипедист', 's_s...",
16,1,Осталось на месте ДТП,Фургоны,Boxer,PEUGEOT,Белый,,Технические неисправности отсутствуют,С передним приводом,2014,"Юридические лица, являющиеся коммерческими орг...","[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...",
17,2,Осталось на месте ДТП,Велосипеды,,,,,Технические неисправности отсутствуют,,,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Велосипедист', 's_s...",
18,1,Осталось на месте ДТП,Фургоны,Porter,HYUNDAI,Белый,,Не устанавливались,С передним приводом,2011,"Юридические лица, являющиеся коммерческими орг...","[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...",
19,2,Осталось на месте ДТП,Велосипеды,,,Иные цвета,,Не устанавливались,Иное расположение рулевого управления,2017,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Велосипедист', 's_s...",

# uch

In [10]:
df_uch = pd.json_normalize(
    json_str,
    record_path=['results', 'region_list', 'pok_list', 'result', 'dtpcardlist', 'info_dtp', 'ts_info', 'ts_uch'],
    meta=[['results', 'region_list', 'pok_list', 'result', 'dtpcardlist', 'info_dtp', 'empt_number'],
          ['results', 'region_list', 'pok_list', 'result', 'dtpcardlist', 'info_dtp', 'ts_info', 't_ts']
         ],
    errors='ignore'
)
df_uch = df_uch.rename(columns={
    'results.region_list.pok_list.result.dtpcardlist.info_dtp.empt_number': 'empt_number',
    'results.region_list.pok_list.result.dtpcardlist.info_dtp.ts_info.t_ts': 't_ts',
})

In [11]:
df_uch.columns

Index(['n_uch', 'kt_uch', 's_sm', 'pol', 's_t', 'npdd', 'sop_npdd',
       'safety_belt', 's_seat_group', 'alco', 'v_st', 'empt_number', 't_ts'],
      dtype='object')

In [12]:
df_uch[6:20]

,n_uch,kt_uch,s_sm,pol,s_t,npdd,sop_npdd,safety_belt,s_seat_group,alco,v_st,empt_number,t_ts
6,2,Водитель,Нет (не скрывался),Мужской,Не пострадал,[Нет нарушений],[Нет нарушений],Нет,,,20,,"Е-класс (высший средний, бизнес-класс) до 4,9 м"
7,1,Велосипедист,Нет (не скрывался),Женский,"Раненый, находящийся (находившийся) на амбула...",[Нарушение требований сигналов светофора],[Управление ТС в состоянии алкогольного опьяне...,Нет,,,99,,Велосипеды
8,1,Велосипедист,Нет (не скрывался),Женский,"Раненый, находящийся (находившийся) на амбула...",[Несоблюдение очередности проезда перекрестков],[Нет нарушений],Нет,,,99,,Велосипеды
9,2,Водитель,Нет (не скрывался),Мужской,Не пострадал,[Нет нарушений],[Другие нарушения ПДД водителем],Нет,,,32,,Фургоны
10,1,Велосипедист,Нет (не скрывался),Не определен,"Раненый, находящийся (находившийся) на стацион...",[Другие нарушения ПДД водителем],[Нет нарушений],Нет,,,99,,Велосипеды
11,2,Водитель,Нет (не скрывался),Мужской,Не пострадал,[Нет нарушений],[Нет нарушений],Нет,,,5,,"D-класс (средний) до 4,6 м"
12,2,Водитель,Нет (не скрывался),Женский,Не пострадал,[Нет нарушений],[Нет нарушений],Нет,,,14,,"С-класс (малый средний, компактный) до 4,3 м"
13,1,Велосипедист,Нет (не скрывался),Мужской,"Раненый, находящийся (находившийся) на амбула...",[Несоблюдение очередности проезда перекрестков],[Нет нарушений],Нет,,,99,,Велосипеды
14,1,Водитель,Нет (не скрывался),Мужской,Не пострадал,[Нарушение правил перестроения],[Нет нарушений],Нет,,,11,,"В-класс (малый) до 3,9 м"
15,2,Велосипедист,Нет (не скрывался),Мужской,"Раненый, находящийся (находившийся) на стацион...",[Нет нарушений],[Нет нарушений],Нет,,,99,,Велосипеды
16,1,Водитель,Нет (не скрывался),Мужской,Не пострадал,[Нет нарушений],[Нет нарушений],Нет,,,16,,Фургоны
17,2,Велосипедист,Нет (не скрывался),Мужской,"Раненый, находящийся (находившийся) на амбула...",[Нарушение правил расположения ТС на проезжей ...,[Нет нарушений],Нет,,,99,,Велосипеды
18,1,Водитель,Нет (не скрывался),Мужской,Не пострадал,[Нет нарушений],[Несоблюдение требований ОСАГО],Нет,,,26,,Фургоны
19,2,Велосипедист,Нет (не скрывался),Мужской,"Раненый, находящийся (находившийся) на амбула...",[Неправильный выбор дистанции],[Нет нарушений],Нет,,,99,,Велосипеды

# merged

In [62]:
df = pd.merge(df_dtp, df_ts, on='empt_number')
df = pd.merge(df, df_uch, on='empt_number')

In [63]:
df.columns

Index(['empt_number', 'date_dtp', 'time', 'coord_w', 'coord_l', 'dtpv', 'k_ts',
       'k_uch', 'pog', 'ran', 's_dtp', 'district', 'house', 'km', 'm', 'np',
       'street', 'dor', 'dor_z', 'dor_k', 'k_ul', 'ts_info', 'uch_info',
       'dor_usl.sdor', 'dor_usl.obj_dtp', 'dor_usl.ndu', 'dor_usl.factor',
       'dor_usl.spog', 'dor_usl.s_pch', 'dor_usl.osv', 'dor_usl.chom',
       'reg_code', 'reg_name', 'pok_code', 'pok_name', 'n_ts', 'ts_s',
       't_ts_x', 'm_ts', 'marka_ts', 'color', 'm_pov', 't_n', 'r_rul', 'g_v',
       'o_pf', 'ts_uch', 'n_uch', 'kt_uch', 's_sm', 'pol', 's_t', 'npdd',
       'sop_npdd', 'safety_belt', 's_seat_group', 'alco', 'v_st', 't_ts_y'],
      dtype='object')

In [64]:
df.head(6)

,empt_number,date_dtp,time,coord_w,coord_l,dtpv,k_ts,k_uch,pog,ran,s_dtp,district,house,km,m,np,street,dor,dor_z,dor_k,k_ul,ts_info,uch_info,dor_usl.sdor,dor_usl.obj_dtp,dor_usl.ndu,dor_usl.factor,dor_usl.spog,dor_usl.s_pch,dor_usl.osv,dor_usl.chom,reg_code,reg_name,pok_code,pok_name,n_ts,ts_s,t_ts_x,m_ts,marka_ts,color,m_pov,t_n,r_rul,g_v,o_pf,ts_uch,n_uch,kt_uch,s_sm,pol,s_t,npdd,sop_npdd,safety_belt,s_seat_group,alco,v_st,t_ts_y
0,450091778,30.05.2026,19:53,55.944814,37.347529,Наезд на велосипедиста,2,2,0,1,810,Молжаниновский,"11, к. 16",0,0,,ул Синявинская,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '1', 'ts_s': 'Осталось на месте ДТП'...",[],[Перегон (нет объектов на месте ДТП)],[Многоквартирные жилые дома],[Не установлены],[Сужение проезжей части припаркованным транспо...,[Ясно],Сухое,Светлое время суток,Движение частично перекрыто,1145,гор. Москва,131,с наездом на велосипедиста (дейст. до 31.12.20...,1,Осталось на месте ДТП,"В-класс (малый) до 3,9 м",Прочие модели Hyundai,HYUNDAI,Белый,,Технические неисправности отсутствуют,С передним приводом,2020,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...",2,Водитель,Нет (не скрывался),Женский,Не пострадал,[Несоответствие скорости конкретным условиям д...,[Нет нарушений],Да,,00,27,"В-класс (малый) до 3,9 м"
1,450091778,30.05.2026,19:53,55.944814,37.347529,Наезд на велосипедиста,2,2,0,1,810,Молжаниновский,"11, к. 16",0,0,,ул Синявинская,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '1', 'ts_s': 'Осталось на месте ДТП'...",[],[Перегон (нет объектов на месте ДТП)],[Многоквартирные жилые дома],[Не установлены],[Сужение проезжей части припаркованным транспо...,[Ясно],Сухое,Светлое время суток,Движение частично перекрыто,1145,гор. Москва,131,с наездом на велосипедиста (дейст. до 31.12.20...,1,Осталось на месте ДТП,"В-класс (малый) до 3,9 м",Прочие модели Hyundai,HYUNDAI,Белый,,Технические неисправности отсутствуют,С передним приводом,2020,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...",1,Водитель,Нет (не скрывался),Мужской,"Раненый, находящийся (находившийся) на амбулат...",[Нет нарушений],[Нет нарушений],Нет,,00,99,Велосипеды (без двигателя)
2,450091778,30.05.2026,19:53,55.944814,37.347529,Наезд на велосипедиста,2,2,0,1,810,Молжаниновский,"11, к. 16",0,0,,ул Синявинская,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '1', 'ts_s': 'Осталось на месте ДТП'...",[],[Перегон (нет объектов на месте ДТП)],[Многоквартирные жилые дома],[Не установлены],[Сужение проезжей части припаркованным транспо...,[Ясно],Сухое,Светлое время суток,Движение частично перекрыто,1145,гор. Москва,131,с наездом на велосипедиста (дейст. до 31.12.20...,2,Осталось на месте ДТП,Велосипеды (без двигателя),Прочие марки и модели ТС,Прочие марки ТС,Желтый,,Технические неисправности отсутствуют,Иное расположение рулевого управления,2020,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...",2,Водитель,Нет (не скрывался),Женский,Не пострадал,[Несоответствие скорости конкретным условиям д...,[Нет нарушений],Да,,00,27,"В-класс (малый) до 3,9 м"
3,450091778,30.05.2026,19:53,55.944814,37.347529,Наезд на велосипедиста,2,2,0,1,810,Молжаниновский,"11, к. 16",0,0,,ул Синявинская,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '1', 'ts_s': 'Осталось на месте ДТП'...",[],[Перегон (нет объектов на месте ДТП)],[Многоквартирные жилые дома],[Не установлены],[Сужение проезжей части припаркованным транспо...,[Ясно],Сухое,Светлое время суток,Движение частично перекрыто,1145,гор. Москва,131,с наездом на велосипедиста (дейст. до 31.12.20...,2,Осталось на месте ДТП,Велосипеды (без двигателя),Прочие марки и модели ТС,Прочие марки ТС,Желтый,,Технические неисправности отсутствуют,Иное расположение рулевого управления,2020,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...",1,Водитель,Нет (не скрывался),Мужской,"Раненый, находящийся (находившийся) на амбулат...",[Нет нарушений],[Нет нарушений],Нет,,00,99,Велосипеды (без двигателя)
4,450090578,28.05.2026,17:00,55.716529,37.892393,Наезд на велосипедиста,2,2,0,1,500,Косино-Ухтомский,37,0,0,п Ухтомский,ул Руднёвка,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '2', 'ts_s': 'Осталось на месте ДТП'...",[],[Выезд с прилегающей территории],[Многоквартирные жилые дома],[Не установлены],[Сведения отсутствуют],[Ясно],Сухое,Светлое время суток,Движение частично перекрыто,1145,гор. Москва,131,с наездом на велосипедиста (дейст. до 31.12.20...,2,Осталось на месте ДТП,Велосипед с электрическим двигателем,Прочие марки и модели ТС,Прочие марки ТС,Черный,,Технические неисправности отсутствуют,Иное расположение рулевого управления,2024,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...",1,Водитель,Нет (не скрывался),Мужской,Получил телесные повреждения с показанием к ле...,[Нет нарушений],[Нет нарушений],Нет,,00,95,Велосипед с электрическим двигателем
5,450090578,28.05.2026,17:00,55.716529,37.892393,Наезд на велосипедиста,2,2,0,1,500,Косино-Ухтомский,37,0,0,п Ухтомский,ул Руднёвка,,"Местного значения (дорога местного значения, в...",,Улицы и дороги местного значения в жилой застр...,"[{'n_ts': '2', 'ts_s': 'Осталось на месте ДТП'...",[],[Выезд с прилегающей территории],[Многоквартирные жилые дома],[Не установлены],[Сведения отсутствуют],[Ясно],Сухое,Светлое время суток,Движение частично перекрыто,1145,гор. Москва,131,с наездом на велосипедиста (дейст. до 31.12.20...,2,Осталось на месте ДТП,Велосипед с электрическим двигателем,Прочие марки и модели ТС,Прочие марки ТС,Черный,,Технические неисправности отсутствуют,Иное расположение рулевого управления,2024,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...",2,Водитель,Нет (не скрывался),Мужской,Не пострадал,[Несоблюдение очередности проезда],[Нет нарушений],Да,,00,0,"В-класс (малый) до 3,9 м"

In [25]:
df[:3]

,empt_number,date_dtp,time,coord_w,coord_l,dtpv,k_ts,k_uch,pog,ran,...,t_ts,m_ts,marka_ts,color,m_pov,t_n,r_rul,g_v,o_pf,ts_uch
0,450091778,30.05.2026,19:53,55.944814,37.347529,Наезд на велосипедиста,2,2,0,1,...,"В-класс (малый) до 3,9 м",Прочие модели Hyundai,HYUNDAI,Белый,,Технические неисправности отсутствуют,С передним приводом,2020,Физические лица,"[{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ..."
1,450091778,30.05.2026,19:53,55.944814,37.347529,Наезд на велосипедиста,2,2,0,1,...,Велосипеды (без двигателя),Прочие марки и модели ТС,Прочие марки ТС,Желтый,,Технические неисправности отсутствуют,Иное расположение рулевого управления,2020,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ..."
2,450090578,28.05.2026,17:00,55.716529,37.892393,Наезд на велосипедиста,2,2,0,1,...,Велосипед с электрическим двигателем,Прочие марки и модели ТС,Прочие марки ТС,Черный,,Технические неисправности отсутствуют,Иное расположение рулевого управления,2024,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ..."

In [26]:
print(df[:5])

  empt_number    date_dtp   time    coord_w    coord_l  \
0   450091778  30.05.2026  19:53  55.944814  37.347529
1   450091778  30.05.2026  19:53  55.944814  37.347529
2   450090578  28.05.2026  17:00  55.716529  37.892393
3   450090578  28.05.2026  17:00  55.716529  37.892393
4   450090131  28.05.2026  10:50  55.569306  37.586418

                     dtpv  k_ts  k_uch  pog  ran  ...  \
0  Наезд на велосипедиста     2      2    0    1  ...
1  Наезд на велосипедиста     2      2    0    1  ...
2  Наезд на велосипедиста     2      2    0    1  ...
3  Наезд на велосипедиста     2      2    0    1  ...
4  Наезд на велосипедиста     2      2    0    1  ...

                                           t_ts                      m_ts  \
0                      В-класс (малый) до 3,9 м     Прочие модели Hyundai
1                    Велосипеды (без двигателя)  Прочие марки и модели ТС
2          Велосипед с электрическим двигателем  Прочие марки и модели ТС
3                      В-класс (малый) до 3,9 м                    Jolion
4  Минивэны и универсалы повышенной вместимости                        RX

          marka_ts   color m_pov                                    t_n  \
0          HYUNDAI   Белый        Технические неисправности отсутствуют
1  Прочие марки ТС  Желтый        Технические неисправности отсутствуют
2  Прочие марки ТС  Черный        Технические неисправности отсутствуют
3            HAVAL   Белый        Технические неисправности отсутствуют
4            EXEED   Серый        Технические неисправности отсутствуют

                                   r_rul   g_v  \
0                    С передним приводом  2020
1  Иное расположение рулевого управления  2020
2  Иное расположение рулевого управления  2024
3                    С передним приводом  2023
4                         Полноприводные  2023

                                                o_pf  \
0                                    Физические лица
1                                    Физические лица
2                                    Физические лица
3  Юридические лица, являющиеся коммерческими орг...
4                                    Физические лица

                                              ts_uch
0  [{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...
1  [{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...
2  [{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...
3  [{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...
4  [{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...

[5 rows x 47 columns]

# explore

## t_ts

In [74]:
t_ts = sorted(df_uch.t_ts.unique())
for i, t in enumerate(t_ts):
    print(i, t)

0
1 D-класс (средний) до 4,6 м
2 S-класс (высший, представительский класс) более 4,9 м
3 А-класс (особо малый) до 3,5 м
4 Автобетоносмесители
5 Автобусы (без типа)
6 Автокраны и транспортные средства, оснащенные кранами-манипуляторами
7 Автомобили скорой медицинской помощи
8 Автоэвакуаторы
9 Бортовые
10 Бортовые грузовые автомобили
11 В-класс (малый) до 3,9 м
12 Велосипед с электрическим двигателем
13 Велосипеды
14 Велосипеды (без двигателя)
15 Е-класс (высший средний, бизнес-класс) до 4,9 м
16 Иные ТС
17 Иные дорожно-строительные и дорожно-эксплуатационные машины и механизмы
18 Иные мототранспортные средства
19 Квадрициклы
20 Квадроциклы
21 Легковые автомобили (без типа)
22 Медицинские комплексы на шасси транспортных средств
23 Минивэны и универсалы повышенной вместимости
24 Моноколеса
25 Мопеды с двигателем внутреннего сгорания более 50 см. куб.
26 Мопеды с двигателем внутреннего сгорания менее 50 см. куб.
27 Мопеды с электродвигателем менее 4 кВт
28 Мотоколяски
29 Мотороллеры
30 Мотоциклы
31 Одноэтажные длиной не более 5 м
32 Одноэтажные длиной от 5 до 8 м
33 Одноэтажные длиной от 8 до 12 м
34 Одноэтажные, сочлененные длиной более 12 м
35 Оснащённые специализированным оборудованием  автотранспортные средства для коммунального хозяйства и  содержания дорог
36 Оснащённые специализированным оборудованием автотранспортные средства аварийно-спасательных служб и полиции
37 Персональное электрическое средство передвижения малой мощности
38 Прочая спецтехника
39 Прочие
40 Прочие грузовые автомобили
41 Прочие легковые автомобили
42 Прочие одноярусные
43 Рефрижераторы
44 С-класс (малый средний, компактный) до 4,3 м
45 Самосвалы
46 Седельные тягачи
47 Спецтехника (без типа)
48 Тракторы
49 Трамваи
50 Транспортные средства для перевозки денежной выручки и ценных грузов
51 Транспортные средства для перевозки пищевых жидкостей
52 Транспортные средства оперативно-служебные для перевозки лиц, находящихся под стражей
53 Трициклы
54 Троллейбусы
55 Фронтальные погрузчики
56 Фургоны
57 Цистерны
58 Шасси
59 Электробусы
60 Электросамокаты

In [78]:
for i, t in enumerate(t_ts):
    if 'вел' in t.lower():
        print(i, t)

12 Велосипед с электрическим двигателем
13 Велосипеды
14 Велосипеды (без двигателя)

In [79]:
df_ts[df_ts['t_ts'] == t_ts[12]].shape[0],\
df_ts[df_ts['t_ts'] == t_ts[13]].shape[0] + df_ts[df_ts['t_ts'] == t_ts[14]].shape[0]

(666, 11738)

In [89]:
df_ts.t_ts.value_counts()[:60]

t_ts
Велосипеды                                                                                                                11009
В-класс (малый) до 3,9 м                                                                                                   4264
С-класс (малый средний, компактный) до 4,3 м                                                                               2295
Прочие легковые автомобили                                                                                                 1342
D-класс (средний) до 4,6 м                                                                                                 1328
Велосипеды (без двигателя)                                                                                                  729
Минивэны и универсалы повышенной вместимости                                                                                711
Велосипед с электрическим двигателем                                                                                        666
А-класс (особо малый) до 3,5 м                                                                                              374
Е-класс (высший средний, бизнес-класс) до 4,9 м                                                                             338
Фургоны                                                                                                                     329
Иные ТС                                                                                                                     227
Мотоциклы                                                                                                                   177
Бортовые грузовые автомобили                                                                                                121
Прочие одноярусные                                                                                                          108
Седельные тягачи                                                                                                             94
                                                                                                                             75
S-класс (высший, представительский класс) более 4,9 м                                                                        69
Самосвалы                                                                                                                    62
Прочая спецтехника                                                                                                           60
Рефрижераторы                                                                                                                49
Одноэтажные длиной от 8 до 12 м                                                                                              48
Прочие грузовые автомобили                                                                                                   43
Бортовые                                                                                                                     37
Одноэтажные длиной от 5 до 8 м                                                                                               34
Электросамокаты                                                                                                              33
Автомобили скорой медицинской помощи                                                                                         31
Мопеды с двигателем внутреннего сгорания менее 50 см. куб.                                                                   28
Полуприцепы прочие                                                                                                           25
Тракторы                                                                                                                     21
Троллейбусы                                                                                                                  17
Одноэтажные, сочлененные длиной более 12 м                                                                                   14
Прицепы прочие                                                                                                               14
Иные мототранспортные средства                                                                                               13
Трамваи                                                                                                                      13
Легковые автомобили (без типа)                                                                                               13
Персональное электрическое средство передвижения малой мощности                                                              13
Оснащённые специализированным оборудованием  автотранспортные средства для коммунального хозяйства и  содержания дорог       11
Мопеды с электродвигателем менее 4 кВт                                                                                       11
Автобетоносмесители                                                                                                          10
Автокраны и транспортные средства, оснащенные кранами-манипуляторами                                                          9
Автоэвакуаторы                                                                                                                9
Квадроциклы                                                                                                                   9
Медицинские комплексы на шасси транспортных средств                                                                           9
Полуприцепы-фургоны                                                                                                           8
Полуприцепы-цистерны                                                                                                          8
Электробусы                                                                                                                   8
Полуприцепы-самосвалы                                                                                                         7
Шасси                                                                                                                         7
Цистерны                                                                                                                      7
Прицепы к легковым автомобилям                                                                                                6
Автобусы (без типа)                                                                                                           4
Спецтехника (без типа)                                                                                                        4
Фронтальные погрузчики                                                                                                        4
Полуприцепы с бортовой платформой                                                                                             4
Одноэтажные длиной не более 5 м                                                                                               4
Прицепы вагоны-дома передвижные                                                                                               2
Прицепы тракторные                                                                                                            2
Транспортные средства оперативно-служебные для перевозки лиц, находящихся под стражей                                         2
Оснащённые специализированным оборудованием автотранспортные средства аварийно-спасательных служб и полиции                   2
Name: count, dtype: int64

## npdd, sop_npdd

In [107]:
df_uch.npdd.value_counts(normalize=True)[:60]

npdd
[Нет нарушений]                                                                                                                                                                                0.479071
[Несоблюдение очередности проезда]                                                                                                                                                             0.175325
[Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                                            0.052313
[Другие нарушения ПДД водителем]                                                                                                                                                               0.039976
[Нарушение правил расположения ТС на проезжей части]                                                                                                                                           0.035690
[Нарушение правил проезда пешеходного перехода]                                                                                                                                                0.034088
[Нарушение требований сигналов светофора]                                                                                                                                                      0.031925
[Несоблюдение очередности проезда перекрестков]                                                                                                                                                0.025796
[Нарушение правил перестроения]                                                                                                                                                                0.024554
[Несоответствие скорости конкретным условиям движения]                                                                                                                                         0.021710
[Несоблюдение бокового интервала]                                                                                                                                                              0.018185
[Неправильный выбор дистанции]                                                                                                                                                                 0.015101
[Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись]                                             0.006609
[Несоблюдение условий, разрешающих движение транспорта задним ходом]                                                                                                                           0.004566
[Непредоставление преимущества в движении пешеходу]                                                                                                                                            0.004326
[Выезд на полосу встречного движения]                                                                                                                                                          0.003925
[Невыполнение требований обеспечения безопасности при начале движения]                                                                                                                         0.003565
[Выезд на полосу встречного движения в местах, где это запрещено]                                                                                                                              0.002924
[Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                            0.002564
[Нарушение требований дорожных знаков]                                                                                                                                                         0.002403
[Превышение установленной скорости движения]                                                                                                                                                   0.002403
[Нарушение правил остановки и стоянки]                                                                                                                                                         0.001562
[Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия]                                                                                                  0.001041
[Нарушение требований линий разметки]                                                                                                                                                          0.001001
[Движение во встречном направлении по дороге с односторонним движением]                                                                                                                        0.000921
[Управление велосипедом с неисправной тормозной системой]                                                                                                                                      0.000681
[Нарушение требований сигналов светофора, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                   0.000641
[Другие нарушения ПДД водителями (не применяется с 12.2020)]                                                                                                                                   0.000561
[Нарушение правил обгона]                                                                                                                                                                      0.000561
[Иные нарушения]                                                                                                                                                                               0.000481
[Непредоставление преимущества при пересечении проезжей части вне перекрестка при движении на велосипеде или СИМ]                                                                              0.000401
[Нарушение правил выезда на встречную полосу в местах, где это разрешено]                                                                                                                      0.000361
[Нарушение правил при круговом движении]                                                                                                                                                       0.000280
[Нарушение требований сигналов светофора, Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись]    0.000280
[Нарушение правил проезда пешеходного перехода, Нарушение требований сигналов светофора]                                                                                                       0.000240
[Несоблюдение очередности проезда, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                          0.000240
[Разворот в местах, где разворот запрещён]                                                                                                                                                     0.000200
[Несоблюдение очередности проезда, Неправильный выбор дистанции]                                                                                                                               0.000200
[Нарушение правил проезда пешеходного перехода, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                             0.000160
[Нарушение правил расположения ТС на проезжей части, Неправильный выбор дистанции]                                                                                                             0.000160
[Неподача или неправильная подача сигналов]                                                                                                                                                    0.000160
[Нарушение правил расположения ТС на проезжей части, Нарушение требований сигналов светофора]                                                                                                  0.000160
[Управление велосипедом с неисправной тормозной системой, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                   0.000160
[Несоответствие скорости конкретным условиям движения, Несоблюдение бокового интервала]                                                                                                        0.000120
[Несоблюдение очередности проезда, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                          0.000080
[Выезд на полосу встречного движения, Нарушение правил проезда пешеходного перехода]                                                                                                           0.000080
[Несоответствие скорости конкретным условиям движения, Другие нарушения ПДД водителем]                                                                                                         0.000080
[Нарушение правил расположения ТС на проезжей части, Нарушение требований линий разметки]                                                                                                      0.000080
[Нарушение правил расположения ТС на проезжей части, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                        0.000080
[Несоблюдение очередности проезда, Нарушение правил проезда пешеходного перехода]                                                                                                              0.000080
[Нарушение требований сигналов светофора, Выезд на полосу встречного движения в местах, где это запрещено]                                                                                     0.000080
[Нарушение требований сигналов светофора, Нарушение требований дорожных знаков]                                                                                                                0.000080
[Выезд на трамвайные пути встречного направления]                                                                                                                                              0.000080
[Другие нарушения ПДД водителем, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                            0.000080
[Эксплуатация технически неисправного ТС (проставляется в случае ДТП по причине технеисправности)]                                                                                             0.000080
[Несоблюдение очередности проезда, Несоблюдение бокового интервала]                                                                                                                            0.000080
[Нарушение правил перестроения, Нарушение требований линий разметки, Другие нарушения ПДД водителем]                                                                                           0.000080
[Нарушение правил перевозки людей]                                                                                                                                                             0.000080
[Управление велосипедом, не оснащённым светоотражающими элементами, Нарушение правил расположения ТС на проезжей части]                                                                        0.000080
[Несоблюдение очередности проезда перекрестков, Нарушение требований дорожных знаков]                                                                                                          0.000080
Name: proportion, dtype: float64

In [103]:
# Что нарушали не велосипедисты
df_uch[(~df_uch['t_ts'].isin(t_ts[12:15])) & (df_uch['npdd'].apply(lambda x: x and 'Нет нарушений' not in x))].npdd.value_counts(normalize=True)

npdd
[Несоблюдение очередности проезда]                                                                                                                    0.418256
[Нарушение правил проезда пешеходного перехода]                                                                                                       0.103509
[Другие нарушения ПДД водителем]                                                                                                                      0.070461
[Несоблюдение очередности проезда перекрестков]                                                                                                       0.066676
[Несоответствие скорости конкретным условиям движения]                                                                                                0.061581
[Несоблюдение бокового интервала]                                                                                                                     0.051827
[Неправильный выбор дистанции]                                                                                                                        0.039016
[Нарушение правил расположения ТС на проезжей части]                                                                                                  0.038579
[Нарушение правил перестроения]                                                                                                                       0.036687
[Нарушение требований сигналов светофора]                                                                                                             0.035667
[Несоблюдение условий, разрешающих движение транспорта задним ходом]                                                                                  0.016596
[Непредоставление преимущества в движении пешеходу]                                                                                                   0.015286
[Превышение установленной скорости движения]                                                                                                          0.008735
[Невыполнение требований обеспечения безопасности при начале движения]                                                                                0.007861
[Нарушение правил остановки и стоянки]                                                                                                                0.005678
[Нарушение требований дорожных знаков]                                                                                                                0.005387
[Выезд на полосу встречного движения]                                                                                                                 0.003348
[Нарушение требований линий разметки]                                                                                                                 0.002038
[Нарушение правил обгона]                                                                                                                             0.001747
[Иные нарушения]                                                                                                                                      0.001601
[Выезд на полосу встречного движения в местах, где это запрещено]                                                                                     0.000873
[Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия]                                                         0.000873
[Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                   0.000728
[Нарушение правил выезда на встречную полосу в местах, где это разрешено]                                                                             0.000582
[Нарушение правил при круговом движении]                                                                                                              0.000582
[Другие нарушения ПДД водителями (не применяется с 12.2020)]                                                                                          0.000437
[Несоответствие скорости конкретным условиям движения, Несоблюдение бокового интервала]                                                               0.000437
[Несоблюдение очередности проезда, Неправильный выбор дистанции]                                                                                      0.000437
[Нарушение правил проезда пешеходного перехода, Другие нарушения ПДД водителем]                                                                       0.000291
[Нарушение правил перестроения, Нарушение требований линий разметки, Другие нарушения ПДД водителем]                                                  0.000291
[Выезд на полосу встречного движения, Нарушение правил проезда пешеходного перехода]                                                                  0.000291
[Несоответствие скорости конкретным условиям движения, Другие нарушения ПДД водителем]                                                                0.000291
[Нарушение правил расположения ТС на проезжей части, Неправильный выбор дистанции]                                                                    0.000291
[Эксплуатация технически неисправного ТС (проставляется в случае ДТП по причине технеисправности)]                                                    0.000291
[Несоблюдение очередности проезда перекрестков, Нарушение требований дорожных знаков]                                                                 0.000291
[Нарушение правил перевозки людей]                                                                                                                    0.000291
[Нарушение требований линий разметки, Нарушение правил расположения ТС на проезжей части]                                                             0.000291
[Движение во встречном направлении по дороге с односторонним движением]                                                                               0.000291
[Разворот в местах, где разворот запрещён]                                                                                                            0.000291
[Нарушение правил проезда пешеходного перехода, Нарушение требований сигналов светофора]                                                              0.000291
[Неподача или неправильная подача сигналов поворота]                                                                                                  0.000291
[Несоблюдение очередности проезда, Нарушение правил проезда пешеходного перехода]                                                                     0.000291
[Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись]    0.000146
[Несоблюдение очередности проезда, Нарушение требований дорожных знаков]                                                                              0.000146
[Создание помех для водителя в управлении транспортным средством]                                                                                     0.000146
Name: proportion, dtype: float64

In [104]:
# Что нарушали велосипедисты (не электро)
df_uch[(df_uch['t_ts'].isin(t_ts[13:15])) & (df_uch['npdd'].apply(lambda x: x and 'Нет нарушений' not in x))].npdd.value_counts(normalize=True)

npdd
[Несоблюдение очередности проезда]                                                                                                                                                                                                                   0.241255
[Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                                                                                                  0.224194
[Нарушение правил расположения ТС на проезжей части]                                                                                                                                                                                                 0.100465
[Другие нарушения ПДД водителем]                                                                                                                                                                                                                     0.088575
[Нарушение требований сигналов светофора]                                                                                                                                                                                                            0.086335
[Нарушение правил перестроения]                                                                                                                                                                                                                      0.058935
[Несоблюдение очередности проезда перекрестков]                                                                                                                                                                                                      0.032052
[Нарушение правил проезда пешеходного перехода]                                                                                                                                                                                                      0.023264
[Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись]                                                                                                   0.021368
[Неправильный выбор дистанции]                                                                                                                                                                                                                       0.017060
[Несоответствие скорости конкретным условиям движения]                                                                                                                                                                                               0.016888
[Несоблюдение бокового интервала]                                                                                                                                                                                                                    0.016026
[Выезд на полосу встречного движения]                                                                                                                                                                                                                0.012924
[Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                                                                                  0.011029
[Выезд на полосу встречного движения в местах, где это запрещено]                                                                                                                                                                                    0.010684
[Невыполнение требований обеспечения безопасности при начале движения]                                                                                                                                                                               0.005342
[Нарушение требований дорожных знаков]                                                                                                                                                                                                               0.003791
[Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия]                                                                                                                                                        0.003102
[Управление велосипедом с неисправной тормозной системой]                                                                                                                                                                                            0.002930
[Нарушение требований сигналов светофора, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                                                         0.002757
[Движение во встречном направлении по дороге с односторонним движением]                                                                                                                                                                              0.002585
[Другие нарушения ПДД водителями (не применяется с 12.2020)]                                                                                                                                                                                         0.001896
[Нарушение требований линий разметки]                                                                                                                                                                                                                0.001379
[Нарушение требований сигналов светофора, Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись]                                                          0.001034
[Несоблюдение очередности проезда, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                                                0.001034
[Нарушение правил проезда пешеходного перехода, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                                                   0.000689
[Неподача или неправильная подача сигналов]                                                                                                                                                                                                          0.000689
[Нарушение правил расположения ТС на проезжей части, Нарушение требований сигналов светофора]                                                                                                                                                        0.000689
[Нарушение правил проезда пешеходного перехода, Нарушение требований сигналов светофора]                                                                                                                                                             0.000689
[Управление велосипедом с неисправной тормозной системой, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                         0.000689
[Непредоставление преимущества при пересечении проезжей части вне перекрестка при движении на велосипеде или СИМ]                                                                                                                                    0.000517
[Непредоставление преимущества в движении пешеходу]                                                                                                                                                                                                  0.000517
[Несоблюдение очередности проезда, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                                                                0.000345
[Разворот в местах, где разворот запрещён]                                                                                                                                                                                                           0.000345
[Несоблюдение очередности проезда, Несоблюдение бокового интервала]                                                                                                                                                                                  0.000345
[Нарушение правил выезда на встречную полосу в местах, где это разрешено]                                                                                                                                                                            0.000345
[Нарушение правил расположения ТС на проезжей части, Неправильный выбор дистанции]                                                                                                                                                                   0.000345
[Нарушение требований сигналов светофора, Выезд на полосу встречного движения в местах, где это запрещено]                                                                                                                                           0.000345
[Выезд на трамвайные пути встречного направления]                                                                                                                                                                                                    0.000345
[Нарушение требований сигналов светофора, Нарушение требований дорожных знаков]                                                                                                                                                                      0.000345
[Нарушение правил расположения ТС на проезжей части, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                              0.000345
[Другие нарушения ПДД водителем, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                                                  0.000345
[Другие нарушения ПДД водителем, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                                                                  0.000345
[Управление велосипедом, не оснащённым светоотражающими элементами, Нарушение правил расположения ТС на проезжей части]                                                                                                                              0.000345
[Нарушение правил расположения ТС на проезжей части, Нарушение требований линий разметки]                                                                                                                                                            0.000345
[Нарушение правил обгона]                                                                                                                                                                                                                            0.000345
[Нарушение правил расположения ТС на проезжей части, Невыполнение требований обеспечения безопасности при начале движения]                                                                                                                           0.000345
[Несоблюдение очередности проезда, Нарушение правил расположения ТС на проезжей части]                                                                                                                                                               0.000345
[Управление велосипедом, не оснащённым светоотражающими элементами, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                               0.000345
[Несоблюдение очередности проезда, Другие нарушения ПДД водителем]                                                                                                                                                                                   0.000345
[Несоблюдение очередности проезда, Нарушение требований линий разметки]                                                                                                                                                                              0.000345
[Непредоставление преимущества в движении ТС, имеющему нанесенные на наружные поверхности специальные цветографические схемы, надписи и обозначения, с одновременно включённым проблесковым маячком синего цвета и специальным звуковым сигналом]    0.000345
[Нарушение требований сигналов регулировщика]                                                                                                                                                                                                        0.000345
[Нарушение правил расположения ТС на проезжей части, Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                                              0.000345
[Нарушение правил при круговом движении]                                                                                                                                                                                                             0.000345
[Несоблюдение очередности проезда, Неправильный выбор дистанции]                                                                                                                                                                                     0.000345
[Нарушение правил проезда остановок трамвая]                                                                                                                                                                                                         0.000172
[Нарушение правил перестроения, Неподача или неправильная подача сигналов]                                                                                                                                                                           0.000172
Name: proportion, dtype: float64

In [106]:
# Что нарушали велосипедисты (электро)
df_uch[(df_uch['t_ts'].isin(t_ts[12:13])) & (df_uch['npdd'].apply(lambda x: x and 'Нет нарушений' not in x))].npdd.value_counts(normalize=True)

npdd
[Несоблюдение очередности проезда]                                                                                                                                                             0.312312
[Нарушение требований сигналов светофора]                                                                                                                                                      0.153153
[Нарушение правил расположения ТС на проезжей части]                                                                                                                                           0.129129
[Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись]                                             0.120120
[Несоответствие скорости конкретным условиям движения]                                                                                                                                         0.063063
[Нарушение правил перестроения]                                                                                                                                                                0.057057
[Неправильный выбор дистанции]                                                                                                                                                                 0.030030
[Непредоставление преимущества при пересечении проезжей части вне перекрестка при движении на велосипеде или СИМ]                                                                              0.021021
[Движение во встречном направлении по дороге с односторонним движением]                                                                                                                        0.018018
[Нарушение правил проезда пешеходного перехода]                                                                                                                                                0.015015
[Выезд на полосу встречного движения в местах, где это запрещено]                                                                                                                              0.015015
[Несоблюдение бокового интервала]                                                                                                                                                              0.015015
[Невыполнение требований обеспечения безопасности при начале движения]                                                                                                                         0.012012
[Нарушение требований линий разметки]                                                                                                                                                          0.009009
[Нарушение правил выезда на встречную полосу в местах, где это разрешено]                                                                                                                      0.009009
[Выезд на полосу встречного движения с разворотом, поворотом налево или объездом препятствия]                                                                                                  0.006006
[Нарушение правил при круговом движении]                                                                                                                                                       0.003003
[Иные нарушения]                                                                                                                                                                               0.003003
[Нарушение требований сигналов светофора, Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись]    0.003003
[Нарушение требований дорожных знаков]                                                                                                                                                         0.003003
[Разворот в местах, где разворот запрещён]                                                                                                                                                     0.003003
Name: proportion, dtype: float64

## 
sop_npdd

In [13]:
df_uch.sop_npdd.value_counts(normalize=True)[:60]

sop_npdd
[Нет нарушений]                                                                                                                                                                                                                                                                                                                                                   0.814380
[Оставление места ДТП]                                                                                                                                                                                                                                                                                                                                            0.045864
[Несоблюдение требований ОСАГО]                                                                                                                                                                                                                                                                                                                                   0.021871
[Другие нарушения ПДД водителем]                                                                                                                                                                                                                                                                                                                                  0.018746
[Пересечение велосипедистом проезжей части по пешеходному переходу]                                                                                                                                                                                                                                                                                               0.018306
[Управление при движении по автодороге велосипедом, гужевой повозкой лицом моложе 14 лет]                                                                                                                                                                                                                                                                         0.011576
[Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                                                                                                                                                                                               0.005728
[Управление ТС в состоянии алкогольного опьянения]                                                                                                                                                                                                                                                                                                                0.004166
[Нарушение правил расположения ТС на проезжей части]                                                                                                                                                                                                                                                                                                              0.003885
[Нарушение правил проезда пешеходного перехода]                                                                                                                                                                                                                                                                                                                   0.003285
[Несоответствие скорости конкретным условиям движения]                                                                                                                                                                                                                                                                                                            0.003124
[Управление ТС в состоянии наркотического опьянения]                                                                                                                                                                                                                                                                                                              0.002684
[Пересечение велосипедистом, лицом, использующим для передвижения СИМ, или водителем мопеда проезжей части по пешеходному переходу, не спешившись]                                                                                                                                                                                                                0.002644
[Управление ТС лицом, не имеющим права на управление ТС]                                                                                                                                                                                                                                                                                                          0.002283
[Несоблюдение требований ОСАГО, Другие нарушения ПДД водителем]                                                                                                                                                                                                                                                                                                   0.002083
[Отказ водителя от прохождения медицинского освидетельствования на состояние опьянения]                                                                                                                                                                                                                                                                           0.001883
[Управление ТС лицом, не имеющим права на управление ТС, Несоблюдение требований ОСАГО]                                                                                                                                                                                                                                                                           0.001722
[Управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средства запрещена]                                                                                                                                                                                                                             0.001482
[Оставление места ДТП, Несоблюдение требований ОСАГО]                                                                                                                                                                                                                                                                                                             0.001482
[Светопропускание стекол менее нормативного]                                                                                                                                                                                                                                                                                                                      0.001202
[Нарушение правил движения в жилых зонах]                                                                                                                                                                                                                                                                                                                         0.001162
[Отсутствие у водителя документов, предусмотренных законодательными и иными НПА]                                                                                                                                                                                                                                                                                  0.001122
[Несоблюдение очередности проезда]                                                                                                                                                                                                                                                                                                                                0.001001
[Нарушение требований дорожных знаков]                                                                                                                                                                                                                                                                                                                            0.000961
[Светопропускание стекол менее нормативного, Несоблюдение требований ОСАГО]                                                                                                                                                                                                                                                                                       0.000881
[Нарушение требований сигналов светофора]                                                                                                                                                                                                                                                                                                                         0.000841
[Выезд на полосу встречного движения]                                                                                                                                                                                                                                                                                                                             0.000801
[Управление ТС в состоянии алкогольного опьянения, Оставление места ДТП]                                                                                                                                                                                                                                                                                          0.000761
[Управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средства запрещена, Другие нарушения ПДД водителем]                                                                                                                                                                                             0.000721
[Управление ТС лицом, не имеющим права на управление ТС, Оставление места ДТП, Несоблюдение требований ОСАГО]                                                                                                                                                                                                                                                     0.000641
[Несоблюдение требований ОСАГО, Эксплуатация незарегистрированного ТС]                                                                                                                                                                                                                                                                                            0.000601
[Управление ТС в состоянии наркотического опьянения, Несоблюдение требований ОСАГО]                                                                                                                                                                                                                                                                               0.000561
[Нарушение режима труда и отдыха водителя]                                                                                                                                                                                                                                                                                                                        0.000521
[Управление ТС лицом, лишенным права управления]                                                                                                                                                                                                                                                                                                                  0.000521
[Управление ТС лицом, не имеющим права на управление ТС, Оставление места ДТП]                                                                                                                                                                                                                                                                                    0.000521
[Управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средства запрещена, Несоблюдение требований ОСАГО]                                                                                                                                                                                              0.000481
[Управление ТС лицом, лишенным права управления, Оставление места ДТП]                                                                                                                                                                                                                                                                                            0.000481
[Эксплуатация незарегистрированного ТС]                                                                                                                                                                                                                                                                                                                           0.000441
[Эксплуатация ТС с техническими неисправностями, при которых запрещается их эксплуатация]                                                                                                                                                                                                                                                                         0.000401
[Нарушение требований линий разметки]                                                                                                                                                                                                                                                                                                                             0.000401
[Движение во встречном направлении по дороге с односторонним движением]                                                                                                                                                                                                                                                                                           0.000361
[Отказ водителя от прохождения медицинского освидетельствования на состояние опьянения, Несоблюдение требований ОСАГО]                                                                                                                                                                                                                                            0.000320
[Несоблюдение требований ОСАГО, Отсутствие у водителя документов, предусмотренных законодательными и иными НПА]                                                                                                                                                                                                                                                   0.000320
[Управление ТС лицом, не имеющим права на управление ТС, Несоблюдение требований ОСАГО, Эксплуатация незарегистрированного ТС]                                                                                                                                                                                                                                    0.000320
[Управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средства запрещена, Несоблюдение требований ОСАГО, Другие нарушения ПДД водителем]                                                                                                                                                              0.000320
[Управление при движении по автодороге велосипедом, гужевой повозкой лицом моложе 14 лет, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                                                                                                      0.000320
[Управление ТС лицом, не имеющим права на управление ТС, Эксплуатация незарегистрированного ТС]                                                                                                                                                                                                                                                                   0.000320
[Оставление места ДТП, Употребление водителем алкогольных напитков, наркотических, психотропных или иных одурманивающих веществ после дорожно-транспортного происшествия, к которому он причастен, до проведения освидетельствования с целью установления состояния опьянения или до принятия решения об освобождении от проведения такого освидетельствовани]    0.000320
[Нарушение правил перестроения]                                                                                                                                                                                                                                                                                                                                   0.000280
[Непредоставление преимущества в движении пешеходу]                                                                                                                                                                                                                                                                                                               0.000280
[Управление велосипедом с неисправной тормозной системой]                                                                                                                                                                                                                                                                                                         0.000280
[Пересечение велосипедистом проезжей части по пешеходному переходу, Управление велосипедом, не оснащённым светоотражающими элементами]                                                                                                                                                                                                                            0.000280
[Превышение установленной скорости движения]                                                                                                                                                                                                                                                                                                                      0.000280
[Управление велосипедом, СИМ или мопедом, не оснащённым светоотражающими элементами]                                                                                                                                                                                                                                                                              0.000280
[Несоблюдение бокового интервала]                                                                                                                                                                                                                                                                                                                                 0.000280

## empt_number

In [31]:
empt = df_uch[df_uch['t_ts'] == 'Трамваи'].empt_number
empt.iloc[0]

'450087852'

In [32]:
df_uch[df_uch['empt_number'] == empt.iloc[0]]

,n_uch,kt_uch,s_sm,pol,s_t,npdd,sop_npdd,safety_belt,s_seat_group,alco,v_st,empt_number,t_ts
27,1,Водитель,Нет (не скрывался),Мужской,"Раненый, находящийся (находившийся) на амбулат...",[Нарушение правил проезда остановок трамвая],[Нет нарушений],Нет,,00,99,450087852,Велосипеды (без двигателя)
28,2,Водитель,Нет (не скрывался),Женский,Не пострадал,[Нет нарушений],[Нет нарушений],Да,,00,7,450087852,Трамваи

In [33]:
df_ts[df_ts['empt_number'] == empt.iloc[0]]

,n_ts,ts_s,t_ts,m_ts,marka_ts,color,m_pov,t_n,r_rul,g_v,o_pf,ts_uch,empt_number
28,2,Осталось на месте ДТП,Велосипеды (без двигателя),Прочие марки и модели ТС,Прочие марки ТС,Зеленый,,Технические неисправности отсутствуют,,,Физические лица,"[{'n_uch': '1', 'kt_uch': 'Водитель', 's_sm': ...",450087852
29,1,Осталось на месте ДТП,Трамваи,Прочие марки и модели ТС,Прочие марки ТС,Многоцветный,,Технические неисправности отсутствуют,Иное расположение рулевого управления,2023,"Юридические лица, являющиеся некоммерческими о...","[{'n_uch': '2', 'kt_uch': 'Водитель', 's_sm': ...",450087852

In [34]:
df_dtp[df_dtp['empt_number'] == empt.iloc[0]]

,empt_number,date_dtp,time,coord_w,coord_l,dtpv,k_ts,k_uch,pog,ran,s_dtp,district,house,km,m,np,street,dor,dor_z,dor_k,k_ul,ts_info,uch_info,dor_usl.sdor,dor_usl.obj_dtp,dor_usl.ndu,dor_usl.factor,dor_usl.spog,dor_usl.s_pch,dor_usl.osv,dor_usl.chom,reg_code,reg_name,pok_code,pok_name
13,450087852,23.05.2026,21:16,55.855209,37.437210,Наезд на велосипедиста,2,2,0,1,820,Северное Тушино,5,0,0,,ул Героев Панфиловцев,,"Местного значения (дорога местного значения, в...",,Магистральные улицы общегородского значения,"[{'n_ts': '2', 'ts_s': 'Осталось на месте ДТП'...",[],[Перегон (нет объектов на месте ДТП)],"[Остановка трамвая, Многоквартирные жилые дома]",[Не установлены],[Сведения отсутствуют],[Ясно],Сухое,"В темное время суток, освещение включено",Режим движения не изменялся,1145,гор. Москва,131,с наездом на велосипедиста (дейст. до 31.12.20...